version: '3.8'

services:
  app:
    build: .
    container_name: go-users
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=users
      - DB_SSL_MODE=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - JWT_SECRET_KEY=your-secret-key
      - JWT_EXPIRATION_HOURS=24
      - LOG_LEVEL=info
      - ENVIRONMENT=development
    command: ["/app/go-users", "migrate", "&&", "/app/go-users", "http-server"]

  postgres:
    image: postgres:14-alpine
    container_name: go-users-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: go-users-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: 